"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# El valor real vive en backend/.env (que no se sube al repo). Ver backend/.env.example.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# En producción se agrega el dominio real por variable de entorno (ej. ALLOWED_HOSTS=mi-app.onrender.com);
# estos tres cubren el desarrollo local sin tener que definir nada en backend/.env.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,192.168.0.141', cast=Csv())

# Render (y hosts parecidos) terminan el HTTPS en su propio proxy y le reenvían la petición a la app
# por HTTP simple, avisando el protocolo original en esta cabecera. Sin esto, Django cree que todo
# llega por HTTP: no marca la cookie de sesión como segura y rechaza el login del admin por CSRF.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Como el dominio de producción no se conoce en desarrollo, viaja por variable de entorno (URL
# completa con "https://", a diferencia de ALLOWED_HOSTS que solo lleva el dominio).
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'daphne',  # debe ir primero: hace que `runserver` sirva ASGI (HTTP + WebSockets)
    'jazzmin',  # antes de admin: le da la piel nueva (menú lateral, iconos, colores de marca)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'pedidos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sirve los estáticos (CSS/JS del admin, incluida la piel de Jazzmin) directo desde la app: con
    # DEBUG=False Django deja de servirlos solo, y en Render no hay un servidor de estáticos aparte.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Los orígenes de desarrollo local siempre están permitidos; los de producción (ej. el panel en
# Netlify) se agregan por variable de entorno, igual que ALLOWED_HOSTS.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://localhost:8081',
    'http://localhost:8082',
    'http://192.168.0.141:8081',
    'http://192.168.0.141:8082',
] + config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# En desarrollo, un token que dura solo 5 minutos (el default) es incómodo para probar.
# En producción real, lo correcto es implementar refresco automático con el refresh token en vez de esto.
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Capa de canales: reparte los avisos entre conexiones. La de memoria solo sirve para desarrollo
# con un único proceso (cambios hechos desde otro proceso, como `manage.py shell`, no se propagan).
# En producción define REDIS_URL para usar Redis (requiere instalar `channels-redis`).
if os.environ.get('REDIS_URL'):
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [os.environ['REDIS_URL']]},
        }
    }
else:
    CHANNEL_LAYERS = {'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}}


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASE_URL vive en backend/.env (postgres://usuario:clave@host:puerto/nombre_bd).
# Sin esa variable, cae en sqlite (por si alguien corre el proyecto sin configurar nada).
import dj_database_url

DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}'),
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'  # "hoy" y "ayer" (ganancias, entregas del día) se cuentan en hora de Ecuador

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Adonde `collectstatic` junta todo para que WhiteNoise lo sirva (se corre en el build de Render).
STATIC_ROOT = BASE_DIR / 'staticfiles'
# El logo y el CSS de marca del admin (backend/static/) se suman a los que trae cada app instalada.
STATICFILES_DIRS = [BASE_DIR / 'static']
# Sin el sufijo "Manifest": una plantilla de Jazzmin referencia una carpeta (no un archivo) como
# estático, y el modo con manifest exige que cada referencia exista de verdad y rompe con un 500.
# Sigue comprimiendo igual; solo se pierde el nombre con hash para el cache-busting automático.
STORAGES = {
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Piel del admin de Django (ver https://django-jazzmin.readthedocs.io/).
JAZZMIN_SETTINGS = {
    'site_title': 'Nelson Express',
    'site_header': 'Nelson Express',
    'site_brand': 'Nelson Express',
    'site_logo': 'img/logo.png',
    'login_logo': 'img/logo.png',
    'site_icon': 'img/logo.png',
    'welcome_sign': 'Panel de administración de Nelson Express',
    'copyright': 'Nelson Express',
    'search_model': ['pedidos.Usuario', 'pedidos.Pedido', 'pedidos.Negocio'],
    'custom_css': 'admin/nelson.css',
    'show_ui_builder': False,
    'icons': {
        'auth.Group': 'fas fa-users-cog',
        'pedidos.Usuario': 'fas fa-user',
        'pedidos.PerfilMotorizado': 'fas fa-motorcycle',
        'pedidos.Tarifa': 'fas fa-dollar-sign',
        'pedidos.Negocio': 'fas fa-store',
        'pedidos.Sucursal': 'fas fa-map-marker-alt',
        'pedidos.Producto': 'fas fa-hamburger',
        'pedidos.Direccion': 'fas fa-home',
        'pedidos.Pedido': 'fas fa-receipt',
    },
    'order_with_respect_to': ['pedidos', 'pedidos.Pedido', 'pedidos.Negocio', 'pedidos.Usuario', 'auth'],
}

JAZZMIN_UI_TWEAKS = {
    'navbar': 'navbar-dark',
    'no_navbar_border': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_flat_style': True,
    'theme': 'flatly',
}

# Imágenes subidas desde el admin (fotos de productos). En producción deben ir a un almacenamiento
# externo (S3, Cloudinary...) porque el disco de muchos hosts se borra al reiniciar.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'pedidos.Usuario'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
