# Generated by Django 6.1.1 on 2026-09-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='destino_referencia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
