# Generated by Django 6.1.1 on 2026-09-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_direccion_referencia_pedido_destino_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
