# Generated by Django 6.1.1 on 2026-09-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmotorizado',
            name='vehiculo_color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='perfilmotorizado',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
