# Generated by Django 6.1.1 on 2026-09-21 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_perfilmotorizado_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minima', models.DecimalField(decimal_places=2, default=2, help_text='Costo mínimo de la carrera (incluye los primeros km).', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('km_incluidos', models.DecimalField(decimal_places=2, default=2, help_text='Kilómetros que cubre la tarifa mínima.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_km_extra', models.DecimalField(decimal_places=2, default='0.50', help_text='Costo de cada kilómetro por encima de los incluidos.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('factor_calles', models.DecimalField(decimal_places=2, default='1.30', help_text='Multiplica la distancia en línea recta para aproximar la distancia por calles.', max_digits=4, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'tarifa',
                'verbose_name_plural': 'tarifa',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
