# Generated by Django 6.1.1 on 2026-09-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_tarifa_y_costo_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Principal', help_text='Ej. Centro, Norte, Mall del Sol.', max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('abierta', models.BooleanField(default=True, help_text='Si está cerrada no recibe pedidos.')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='pedidos.negocio')),
            ],
            options={
                'verbose_name_plural': 'sucursales',
                'ordering': ['negocio', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.sucursal'),
        ),
    ]
