# Generated by Django 6.1.1 on 2026-09-21 21:52

import django.core.validators
from django.db import migrations, models
from django.db.models import F


def fecha_de_entrega(apps, schema_editor):
    """Los pedidos ya entregados usan su última actualización como fecha de entrega."""
    Pedido = apps.get_model('pedidos', 'Pedido')
    Pedido.objects.filter(estado='ENTREGADO', entregado_en__isnull=True).update(entregado_en=F('actualizado_en'))



class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_producto_imagen_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Porcentaje de cada carrera que el motorizado entrega a la empresa.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RunPython(fecha_de_entrega, migrations.RunPython.noop),
    ]
