# Generated by Django 6.1.1 on 2026-09-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_ganancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
