# Generated by Django 6.1.1 on 2026-09-22 17:55

from django.db import migrations, models


def copiar_rol_a_banderas(apps, schema_editor):
    """El rol de cada cuenta ya existente se traduce a la bandera equivalente (una sola vez)."""
    Usuario = apps.get_model('pedidos', 'Usuario')
    Usuario.objects.filter(rol='MOTORIZADO').update(es_motorizado=True)
    Usuario.objects.filter(rol='ADMIN').update(es_despachador=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_encargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_despachador',
            field=models.BooleanField(default=False, help_text='Puede entrar al panel de despacho.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_motorizado',
            field=models.BooleanField(default=False, help_text='Puede entrar a la app de motorizados.'),
        ),
        migrations.RunPython(copiar_rol_a_banderas, migrations.RunPython.noop),
    ]
