# Generated by Django 6.1.1 on 2026-09-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_contactos_recogida_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='imagen',
            field=models.CharField(blank=True, help_text='Nombre del archivo en pedidos/static/negocios/ (ej. don-pollo.png). Se sube al repo, no aquí.', max_length=100),
        ),
    ]
